{
  'created_at': 'Wed Dec 19 21:13:29 +0000 2018',
  'id': 1075499385281265664,
  'id_str': '1075499385281265664',
  'text': 'RT @navalny: Как же так? Парковку в центре только что сделали самой дорогой в Европе, а пробки все равно остались. Водители, произошла чудо…',
  'source': '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>',
  'truncated': False,
  'in_reply_to_status_id': None,
  'in_reply_to_status_id_str': None,
  'in_reply_to_user_id': None,
  'in_reply_to_user_id_str': None,
  'in_reply_to_screen_name': None,
  'user': {
    'id': 1070777285924569089,
    'id_str': '1070777285924569089',
    'name': 'Kuzya',
    'screen_name': 'Kuzya38268259',
    'location': None,
    'url': None,
    'description': None,
    'translator_type': 'none',
    'protected': False,
    'verified': False,
    'followers_count': 0,
    'friends_count': 0,
    'listed_count': 0,
    'favourites_count': 0,
    'statuses_count': 33,
    'created_at': 'Thu Dec 06 20:29:33 +0000 2018',
    'utc_offset': None,
    'time_zone': None,
    'geo_enabled': False,
    'lang': 'en',
    'contributors_enabled': False,
    'is_translator': False,
    'profile_background_color': 'F5F8FA',
    'profile_background_image_url': '',
    'profile_background_image_url_https': '',
    'profile_background_tile': False,
    'profile_link_color': '1DA1F2',
    'profile_sidebar_border_color': 'C0DEED',
    'profile_sidebar_fill_color': 'DDEEF6',
    'profile_text_color': '333333',
    'profile_use_background_image': True,
    'profile_image_url': 'http://abs.twimg.com/sticky/default_profile_images/default_profile_normal.png',
    'profile_image_url_https': 'https://abs.twimg.com/sticky/default_profile_images/default_profile_normal.png',
    'default_profile': True,
    'default_profile_image': False,
    'following': None,
    'follow_request_sent': None,
    'notifications': None
  },
  'geo': None,
  'coordinates': None,
  'place': None,
  'contributors': None,
  'retweeted_status': {
    'created_at': 'Wed Dec 19 16:32:52 +0000 2018',
    'id': 1075428765931659264,
    'id_str': '1075428765931659264',
    'text': 'Как же так? Парковку в центре только что сделали самой дорогой в Европе, а пробки все равно остались. Водители, про… https://t.co/x0c13v8DVD',
    'display_text_range': [0, 140],
    'source': '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
    'truncated': True,
    'in_reply_to_status_id': None,
    'in_reply_to_status_id_str': None,
    'in_reply_to_user_id': None,
    'in_reply_to_user_id_str': None,
    'in_reply_to_screen_name': None,
    'user': {
      'id': 82299300,
      'id_str': '82299300',
      'name': 'Alexey Navalny',
      'screen_name': 'navalny',
      'location': 'Moscow',
      'url': 'http://navalny.com/',
      'description': 'Основатель Фонда борьбы с коррупцией, лидер партии Россия Будущего.',
      'translator_type': 'none',
      'protected': False,
      'verified': True,
      'followers_count': 2096988,
      'friends_count': 1068,
      'listed_count': 7751,
      'favourites_count': 2911,
      'statuses_count': 115068,
      'created_at': 'Wed Oct 14 07:12:44 +0000 2009',
      'utc_offset': None,
      'time_zone': None,
      'geo_enabled': False,
      'lang': 'ru',
      'contributors_enabled': False,
      'is_translator': False,
      'profile_background_color': 'C0DEED',
      'profile_background_image_url': 'http://abs.twimg.com/images/themes/theme1/bg.png',
      'profile_background_image_url_https': 'https://abs.twimg.com/images/themes/theme1/bg.png',
      'profile_background_tile': False,
      'profile_link_color': '1DA1F2',
      'profile_sidebar_border_color': 'C0DEED',
      'profile_sidebar_fill_color': 'DDEEF6',
      'profile_text_color': '333333',
      'profile_use_background_image': True,
      'profile_image_url': 'http://pbs.twimg.com/profile_images/980761782909272064/h-qrVrmY_normal.jpg',
      'profile_image_url_https': 'https://pbs.twimg.com/profile_images/980761782909272064/h-qrVrmY_normal.jpg',
      'profile_banner_url': 'https://pbs.twimg.com/profile_banners/82299300/1386663884',
      'default_profile': True,
      'default_profile_image': False,
      'following': None,
      'follow_request_sent': None,
      'notifications': None
    },
    'geo': None,
    'coordinates': None,
    'place': None,
    'contributors': None,
    'quoted_status_id': 1075413722804285440,
    'quoted_status_id_str': '1075413722804285440',
    'quoted_status': {
      'created_at': 'Wed Dec 19 15:33:06 +0000 2018',
      'id': 1075413722804285440,
      'id_str': '1075413722804285440',
      'text': 'Москва встала в\xa09-балльных пробках https://t.co/v7TAZGBGD4',
      'source': '<a href="https://dlvrit.com/" rel="nofollow">dlvr.it</a>',
      'truncated': False,
      'in_reply_to_status_id': None,
      'in_reply_to_status_id_str': None,
      'in_reply_to_user_id': None,
      'in_reply_to_user_id_str': None,
      'in_reply_to_screen_name': None,
      'user': {
        'id': 68643775,
        'id_str': '68643775',
        'name': 'Новости Эхо Москвы',
        'screen_name': 'EchoMskNews',
        'location': 'Moscow',
        'url': 'http://www.echo.msk.ru/news/',
        'description': 'Новости Эхо Москвы ||| Echo of Moscow Radio News',
        'translator_type': 'none',
        'protected': False,
        'verified': False,
        'followers_count': 254629,
        'friends_count': 16,
        'listed_count': 3252,
        'favourites_count': 0,
        'statuses_count': 465294,
        'created_at': 'Tue Aug 25 08:26:22 +0000 2009',
        'utc_offset': None,
        'time_zone': None,
        'geo_enabled': False,
        'lang': 'ru',
        'contributors_enabled': False,
        'is_translator': False,
        'profile_background_color': '9AE4E8',
        'profile_background_image_url': 'http://abs.twimg.com/images/themes/theme1/bg.png',
        'profile_background_image_url_https': 'https://abs.twimg.com/images/themes/theme1/bg.png',
        'profile_background_tile': False,
        'profile_link_color': '666363',
        'profile_sidebar_border_color': 'E6717C',
        'profile_sidebar_fill_color': 'E6717C',
        'profile_text_color': '030303',
        'profile_use_background_image': True,
        'profile_image_url': 'http://pbs.twimg.com/profile_images/799242429966782464/jlpLMLmM_normal.jpg',
        'profile_image_url_https': 'https://pbs.twimg.com/profile_images/799242429966782464/jlpLMLmM_normal.jpg',
        'profile_banner_url': 'https://pbs.twimg.com/profile_banners/68643775/1479387825',
        'default_profile': False,
        'default_profile_image': False,
        'following': None,
        'follow_request_sent': None,
        'notifications': None
      },
      'geo': None,
      'coordinates': None,
      'place': None,
      'contributors': None,
      'is_quote_status': False,
      'quote_count': 3,
      'reply_count': 3,
      'retweet_count': 1,
      'favorite_count': 7,
      'entities': {
        'hashtags': [],
        'urls': [{
          'url': 'https://t.co/v7TAZGBGD4',
          'expanded_url': 'https://echo.msk.ru/news/2336845-echo.html?utm_source=dlvr.it&utm_medium=twitter',
          'display_url': 'echo.msk.ru/news/2336845-e…',
          'indices': [35, 58]
        }],
        'user_mentions': [],
        'symbols': []
      },
      'favorited': False,
      'retweeted': False,
      'possibly_sensitive': False,
      'filter_level': 'low',
      'lang': 'ru'
    },
    'quoted_status_permalink': {
      'url': 'https://t.co/Q7kY3yjhkq',
      'expanded': 'https://twitter.com/echomsknews/status/1075413722804285440',
      'display': 'twitter.com/echomsknews/st…'
    },
    'is_quote_status': True,
    'extended_tweet': {
      'full_text': 'Как же так? Парковку в центре только что сделали самой дорогой в Европе, а пробки все равно остались. Водители, произошла чудовищная ошибка, немедленно покиньте пробку. https://t.co/Q7kY3yjhkq',
      'display_text_range': [0, 168],
      'entities': {
        'hashtags': [],
        'urls': [{
          'url': 'https://t.co/Q7kY3yjhkq',
          'expanded_url': 'https://twitter.com/echomsknews/status/1075413722804285440',
          'display_url': 'twitter.com/echomsknews/st…',
          'indices': [169, 192]
        }],
        'user_mentions': [],
        'symbols': []
      }
    },
    'quote_count': 16,
    'reply_count': 86,
    'retweet_count': 175,
    'favorite_count': 695,
    'entities': {
      'hashtags': [],
      'urls': [{
        'url': 'https://t.co/x0c13v8DVD',
        'expanded_url': 'https://twitter.com/i/web/status/1075428765931659264',
        'display_url': 'twitter.com/i/web/status/1…',
        'indices': [117, 140]
      }],
      'user_mentions': [],
      'symbols': []
    },
    'favorited': False,
    'retweeted': False,
    'possibly_sensitive': False,
    'filter_level': 'low',
    'lang': 'ru'
  },
  'quoted_status_id': 1075413722804285440,
  'quoted_status_id_str': '1075413722804285440',
  'quoted_status': {
    'created_at': 'Wed Dec 19 15:33:06 +0000 2018',
    'id': 1075413722804285440,
    'id_str': '1075413722804285440',
    'text': 'Москва встала в\xa09-балльных пробках https://t.co/v7TAZGBGD4',
    'source': '<a href="https://dlvrit.com/" rel="nofollow">dlvr.it</a>',
    'truncated': False,
    'in_reply_to_status_id': None,
    'in_reply_to_status_id_str': None,
    'in_reply_to_user_id': None,
    'in_reply_to_user_id_str': None,
    'in_reply_to_screen_name': None,
    'user': {
      'id': 68643775,
      'id_str': '68643775',
      'name': 'Новости Эхо Москвы',
      'screen_name': 'EchoMskNews',
      'location': 'Moscow',
      'url': 'http://www.echo.msk.ru/news/',
      'description': 'Новости Эхо Москвы ||| Echo of Moscow Radio News',
      'translator_type': 'none',
      'protected': False,
      'verified': False,
      'followers_count': 254629,
      'friends_count': 16,
      'listed_count': 3252,
      'favourites_count': 0,
      'statuses_count': 465294,
      'created_at': 'Tue Aug 25 08:26:22 +0000 2009',
      'utc_offset': None,
      'time_zone': None,
      'geo_enabled': False,
      'lang': 'ru',
      'contributors_enabled': False,
      'is_translator': False,
      'profile_background_color': '9AE4E8',
      'profile_background_image_url': 'http://abs.twimg.com/images/themes/theme1/bg.png',
      'profile_background_image_url_https': 'https://abs.twimg.com/images/themes/theme1/bg.png',
      'profile_background_tile': False,
      'profile_link_color': '666363',
      'profile_sidebar_border_color': 'E6717C',
      'profile_sidebar_fill_color': 'E6717C',
      'profile_text_color': '030303',
      'profile_use_background_image': True,
      'profile_image_url': 'http://pbs.twimg.com/profile_images/799242429966782464/jlpLMLmM_normal.jpg',
      'profile_image_url_https': 'https://pbs.twimg.com/profile_images/799242429966782464/jlpLMLmM_normal.jpg',
      'profile_banner_url': 'https://pbs.twimg.com/profile_banners/68643775/1479387825',
      'default_profile': False,
      'default_profile_image': False,
      'following': None,
      'follow_request_sent': None,
      'notifications': None
    },
    'geo': None,
    'coordinates': None,
    'place': None,
    'contributors': None,
    'is_quote_status': False,
    'quote_count': 3,
    'reply_count': 3,
    'retweet_count': 1,
    'favorite_count': 7,
    'entities': {
      'hashtags': [],
      'urls': [{
        'url': 'https://t.co/v7TAZGBGD4',
        'expanded_url': 'https://echo.msk.ru/news/2336845-echo.html?utm_source=dlvr.it&utm_medium=twitter',
        'display_url': 'echo.msk.ru/news/2336845-e…',
        'indices': [35, 58]
      }],
      'user_mentions': [],
      'symbols': []
    },
    'favorited': False,
    'retweeted': False,
    'possibly_sensitive': False,
    'filter_level': 'low',
    'lang': 'ru'
  },
  'quoted_status_permalink': {
    'url': 'https://t.co/Q7kY3yjhkq',
    'expanded': 'https://twitter.com/echomsknews/status/1075413722804285440',
    'display': 'twitter.com/echomsknews/st…'
  },
  'is_quote_status': True,
  'quote_count': 0,
  'reply_count': 0,
  'retweet_count': 0,
  'favorite_count': 0,
  'entities': {
    'hashtags': [],
    'urls': [],
    'user_mentions': [{
      'screen_name': 'navalny',
      'name': 'Alexey Navalny',
      'id': 82299300,
      'id_str': '82299300',
      'indices': [3, 11]
    }],
    'symbols': []
  },
  'favorited': False,
  'retweeted': False,
  'filter_level': 'low',
  'lang': 'ru',
  'timestamp_ms': '1545254009920'
}